# Generated by Django 5.2.12 on 2026-04-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.FloatField(default=50),
        ),
    ]
